# -*- coding: utf-8 -*-
"""test_USA_emisssions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GSYVurI4WkzesJ9S-WGdX1P16RPeNtl

# Importing libraries and loading the data
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
import os

!pip install plotly==4.8
import plotly.express as px
import plotly
plotly.__version__

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

data = pd.read_excel('./drive/MyDrive/USA-Emissions.xlsx', index_col='year')
data.head()

data = data[data.index >= 1800]
data

data.columns

fig = plt.subplots(figsize=(12,8))
sns.heatmap(data.isnull(),cbar=False,cmap = 'viridis');

# co2, prct, abs, percapita, population
# shareglobal, cumulative, sharegloablCumulative?


# cement, coal,flaring, gas, oil,
# gdp?

"""## Making a subset based on the columns with values across all the years"""

testdata = data[['co2','co2_growth_prct','co2_growth_abs','co2_per_capita','population','share_global_co2', 'cumulative_co2']]
testdata

"""# Descriptive Analysis on the subset of data"""

testdata.shape

testdata.columns

"""Plotting for any missing values."""

fig = plt.subplots(figsize=(12,8))
sns.heatmap(testdata.isnull(),cbar=False,cmap = 'viridis');

# cement, coal,flaring, gas, oil,
# gdp?

"""We're having one missing value at the start of co2_growth_prct

As this variable equals to percentage change in co2 emissions relative to the previous year, the very first value is Null.
"""

testdata.describe()

"""* By comparing the mean and median values of each column, we can get a rough estimate of the distributions of values in each column.
* The columnns co2, population show that the mean values are much larger than the median values.

# Exploratory Data Analysis

## CO2
"""

fig = px.box(testdata,y='co2',points='all',)
# fig = px.box(testdata,y='population',points='outliers')
# fig = px.box(testdata,y='co2')
fig.update_layout(width=800)
fig.show()

"""With the box plot above, we can check how the values are spread.

Hovering over the boxes, you can see the values from min to median to max.

Also values of all the points are shown to the left. As the max value does not go beyond the whisker line, we should estimate there are no outliers. We can also confirm it by changing the _points_ parameter to 'outliers'. It will not show any points.
"""

testdata_reset = testdata.reset_index()

fig = px.line(testdata_reset,x='year',y='co2')
fig.update_layout(width=800)
fig.show()

"""The sudden declines such as (1929-1933, 1978-1982) might be due to the great depression era, the inflations in late 70s, respectively.

The decades 1960s and 1980s show steep rise. The economy was also on rise that time.

After the peak of 6130.55 in 2005, the values seem to be decreasing after 2007. Maybe due to Obama gov policies.

## Absolute and percentage growth
"""

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=3, cols=1)

fig.append_trace(go.Scatter(
    x=testdata.index,
    y=testdata['co2'],
    name='co2'
), row=1, col=1)

fig.append_trace(go.Scatter(
    x=testdata.index,
    y=testdata['co2_growth_prct'],
    name = "co2_growth_prct"
), row=2, col=1)

fig.append_trace(go.Scatter(
    x=testdata.index,
    y=testdata['co2_growth_abs'],
    name='co2_growth_abs'
), row=3, col=1)


fig.update_layout(height=600, width=800, title_text="Stacked!")
fig.show()

"""The second and third graphs show percent and absolute changes in the values, relative to the previous year, respectively.

## Per capita values
"""

fig = make_subplots(rows=3, cols=1)

fig.append_trace(go.Scatter(
    x=testdata.index,
    y=testdata['co2'],
    name='co2'
), row=1, col=1)

fig.append_trace(go.Scatter(
    x=testdata.index,
    y=testdata['population'],
    name = "population"
), row=2, col=1)

fig.append_trace(go.Scatter(
    x=testdata.index,
    y=testdata['co2_per_capita'],
    name='co2_per_capita'
), row=3, col=1)


fig.update_layout(height=600, width=800, title_text="Stacked!")
fig.show()

"""As expcted, we see can see that both the co2 and co2_per_capita variables show mostly similar trends. 

But the co2_per_capita variable peaks at 22.133 in 1973.

After 2007, it keeps on decreasing.

## Global share
"""

fig = px.line(testdata_reset,x='year',y='share_global_co2')
fig.update_layout(width=800)
fig.show()

"""Years 1926 to 1938 show steady decline in the global share of co2 emissions for USA.

After which it starts to increase rapidly and peaks at 54.35 in the year 1945.

It may mean that many other countries started emitting co2 more rapidly than before.
"""

fig = px.box(testdata_reset,y='share_global_co2',points='all')
fig.update_layout(width=800)
fig.show()

"""No outliers present here too.

# Looking for relationships
"""

# px.density_heatmap()
fig = px.scatter(data_frame=testdata_reset,x=testdata_reset['population'],y=testdata_reset['co2'],color='year')
fig.update_layout(width=800)
fig.show()

fig = px.density_heatmap(testdata_reset,x='co2',y='population')
fig.update_layout(width=800)
fig.show()

